import:
	java.util.Date
	java.text.SimpleDateFormat
	java.lang.System
	org.bukkit.entity.Player
	org.bukkit.Bukkit
	org.bukkit.Location
	org.bukkit.Material


function dropper_convert_date(date_1: number, date_2: number) :: text:
	set {_pattern} to "mm:ss.SSS"
	set {_format} to new SimpleDateFormat({_pattern})
	set {_formattedtime} to {_format}.format(new Date({_date_1}-{_date_2}))
	return {_formattedtime}