command /gingibug <player> <text>:
	trigger:
		clear {dropper::player::%uuid of arg 1%::stats::pb::%arg 2%::splits::*}
		set {dropper::player::%uuid of arg 1%::stats::pb::%arg 2%::splits::1} to "00:05.065"
		set {dropper::player::%uuid of arg 1%::stats::pb::%arg 2%::splits::2} to "00:05.698"
		set {dropper::player::%uuid of arg 1%::stats::pb::%arg 2%::splits::3} to "00:05.015"
		set {dropper::player::%uuid of arg 1%::stats::pb::%arg 2%::splits::4} to "00:05.700"
		set {dropper::player::%uuid of arg 1%::stats::pb::%arg 2%::splits::5} to "00:05.017"
# 	make player execute command "/gamerule doFireTick false"
# 	make player execute command "/gamerule randomTickSpeed 0"