command /fakepb: 
	trigger:
		set {dropper::player::%uuid of player%::stats::pb::fantasy::mapset::*} to "king", "kingdom", "floating", "maelstrom" and "hell"
		set {dropper::player::%uuid of player%::stats::pb::fantasy::splits::*} to "00:05.645", "00:07.645", "00:04.254", "00:02.145" and "00:10.542"

command /clearpb2 <text>:
	trigger:
		clear {dropper::player::%uuid of player%::stats::pb::%arg%::*}
		clear {dropper::player::%uuid of player%::stats::pb::%arg%}